### ISSUE TITLE
BUG | Song artwork not shown

### ISSUE THREAD

**Issue by XeCrash** [zephraOSS/Apple-Music-RPC#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

no artwork shows its just the default apple logo no matter what, i tried on the latest stable v4.1
and the latest v4.2.0-beta3 same result

### Expected Behavior

The artwork should appear for local files on iTunes. But it doesnt

### Steps To Reproduce

1. All the time while its running
2. It wont display album cover art

### Environment

```markdown
- OS: Windows
- Version: 11
```

**Comment by XeCrash** [comment]
[main.log](https://github.com/zephraOSS/Apple-Music-RPC/files/11568842/main.log)

**Comment by N0chteil** [comment]
Not a bug

[Discord thread](https://discord.com/channels/518389564340043776/1111158925664976967)

**Comment by N0chteil** [comment]
Not a bug

[Discord thread](https://discord.com/channels/518389564340043776/1111158925664976967)
