### ISSUE TITLE
BUG | ARM64 Version damaged or broken

### ISSUE THREAD

**Issue by JimDude7404** [zephraOSS/Apple-Music-RPC#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The app does not work at all on my M1 Macbook Air. It just says its damaged or broken, downloading the x64 version does allow it to open but thats not ideal.

### Expected Behavior

The app opens. 

### Steps To Reproduce

1. Download ARM64 version
2. Attempt to open

### Environment

```markdown
- OS: MacOS 13.3.1
- Version: 4.2.0
```

**Comment by N0chteil** [comment]
@JimDude7404 *friendly reminder*

**Comment by JimDude7404** [comment]
Hello, I have switched away from Apple Music so this is no longer needed. Thanks for your help!
