### ISSUE TITLE
BUG | AMR-88 | Timestamps disappear when song is on repeat

### ISSUE THREAD

**Issue by raydiantly** [zephraOSS/Apple-Music-RPC#32]
Whenever a song is on repeat, the timestamps in the discord rich presence will disappear as soon as it repeats for the first time.

**Comment by N0chteil** [comment]
I was hoping no one would notice, but now I have to fix it 😅

**Comment by N0chteil** [comment]
- Fixed with 0ffd13c
- Release fix: v4.2.1
