### ISSUE TITLE
BUG | AMRPC installer damaged

### ISSUE THREAD

**Issue by WEcompany36** [zephraOSS/Apple-Music-RPC#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On Apple Silicon if you open AMRPC with the Arm64 version, you get the error "“AMRPC” is damaged and can’t be opened. You should move it to the Trash."

### Expected Behavior

I expect to use the app when using the Apple Silicon version on a Apple Silicon Mac.

### Steps To Reproduce

1. On a Apple Silicon Mac
2. Download the arm64 version, it doesn't matter if its the dmg or the zip file, it does the same thing
3. Download it to the Applications folder
4. Open it

### Environment

```markdown
- OS: macOS Sonoma 14.1
- Version: 4.2.0
```

### Anything else?

![Screenshot 2023-10-24 at 10 36 09 PM](https://github.com/zephraOSS/Apple-Music-RPC/assets/79947933/e9f6abb9-3515-4cfe-a341-b38d5f699baa)

**Comment by WEcompany36** [comment]
I looked at the latest 4.3.0 Beta 3, and it does the same behavior.

**Comment by N0chteil** [comment]
Please try the steps listed in our documentation: https://docs.amrpc.zephra.org/installation/macos

**Comment by N0chteil** [comment]
@WEcompany36 Please let me know if this fixed your problem :)

**Comment by N0chteil** [comment]
If this issue persists, please lmk
