### ISSUE TITLE
BUG | It cannot detect the iTunes app

### ISSUE THREAD

**Issue by mpratsaki** [zephraOSS/Apple-Music-RPC#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Even though I have iTunes installed, it says "The Music app could not be found. Please make sure that the Music app is installed."

### Environment

```markdown
- OS:Windows 11
- Version: 10.0.22621
```

**Comment by N0chteil** [comment]
@mpratsaki open AMRPC Settings -> Advanced -> disable `Check if Music is installed` -> restart AMRPC

**Comment by mpratsaki** [comment]
> @mpratsaki open AMRPC Settings -> Advanced -> disable `Check if Music is installed` -> restart AMRPC

I can't find the Advanced section

**Comment by N0chteil** [comment]
> > @mpratsaki open AMRPC Settings -> Advanced -> disable `Check if Music is installed` -> restart AMRPC
> 
> I can't find the Advanced section

Which AMRPC version do you have installed?

**Comment by mpratsaki** [comment]
> > > @mpratsaki open AMRPC Settings -> Advanced -> disable `Check if Music is installed` -> restart AMRPC
> > 
> > 
> > I can't find the Advanced section
> 
> Which AMRPC version do you have installed?

I have v4.3.0

![image](https://github.com/zephraOSS/Apple-Music-RPC/assets/110930793/cdeef5fc-4d36-48a3-b2ec-81004dcb60d1)

**Comment by MashyLatte** [comment]
I had the same problem and it worked! Thank you very much
